# Use this strategy for client services
# include it to devise.rb under initializers
#   require './app/lib/oauth2_strategy'
#   config.omniauth :popug_auth, strategy_class: ::OmniAuth::Strategies::Popug_auth
#   config.omniauth :popug_auth, ENV['OAUTH_UID'], ENV['OAUTH_SECRET']
#
# OAUTH_UID and OAUTH_SECRET are generated by doorkeeper

require 'omniauth-oauth2'

module OmniAuth
  module Strategies
    class Popug_auth < OmniAuth::Strategies::OAuth2
      option :name, :popug_auth

      option :client_options, {
          :site => 'http://localhost:3000',
          :authorize_url => 'http://localhost:3000/oauth/authorize',
      }

      uid { raw_info['id'] }

      info do
        {
            :public_id => raw_info['id'],
            :email => raw_info['email'],
            :full_name => raw_info['full_name'],
            :position => raw_info['position'],
            :active => raw_info['active'],
            :role => raw_info['role']
        }
      end

      def raw_info
        @raw_info ||= access_token.get('/accounts/current').parsed
      end
    end
  end
end
